all:
  flowpagos:
    url_exito: 'URL/exito'
    url_fracaso: 'URL/fracaso'
    url_confirmacion: 'URL/confirmar'
    url_pago: 'http://flow.tuxpan.com/app/kpf/pago.php' #DEV
    key: %SF_DATA_DIR%/keys/comercio.pem
    log_path: %SF_LOG_DIR%
    comercio: 'email@comercio-dev.com'

    ## TASA COMISION
    ## Ahora se modifica en sitio de usuario Flow
    ##

    ## TIPO INTEGRACION WEBPAY (solo funciona si solo webpay está seleccionado)
    ## 'f': mostrar pasarela Flow
    ## 'd': directo a webpay
    tipo_integracion: 'd'

    ## MEDIOS DE PAGO
    ## Solo Webpay = 1
    ## Solo Servipag = 2
    ## Todos los medios de pago = 9
    mediopago: 9

# prod:
  # flowpagos:
    # url_pago: 'https://www.flow.cl/app/kpf/pago.php'
    # comercio: 'email@comercio-prod.com'